/* Generated By:JJTree: Do not edit this line. YANG_Belong.java */

public class YANG_Belong extends SimpleNode implements YANG_Header{

    private String belong = null;

  public YANG_Belong(int id) {
    super(id);
  }

  public YANG_Belong(yang p, int id) {
    super(p, id);
  }

    public void setBelong(String b){
	belong = b;
    }
    
    public String getBelong(){
    	return belong;
    }

    public String toString(){
	return "belongs-to " + belong + ";";
    }

}
