import java.util.regex.Matcher;
import java.util.regex.Pattern;

/* Generated By:JJTree: Do not edit this line. YANG_Prefix.java */

public class YANG_Prefix extends SimpleNode implements YANG_Header {

	private String prefix = null;

	public YANG_Prefix(int id) {
		super(id);
	}

	public YANG_Prefix(yang p, int id) {
		super(p, id);
	}

	public void setPrefix(String p) throws YangParserException {
		checkPrefix(p);
	}

	public String getPrefix() {
		return prefix;
	}

	public String toString() {
		return "prefix " + prefix + ";";
	}

	private void checkPrefix(String p) throws YangParserException {
		String lp = YangBuiltInTypes.removeQuotes(p);
		lp = lp.trim();
		if (lp.length() > YangBuiltInTypes.idlength)
			throw new YangParserException("@" + getLine() + ":" + getCol()
					+ ":prefix identifier too long (>63)");
		Pattern pat = Pattern.compile("[a-zA-Z](\\w|\\-)*");
		Matcher m = pat.matcher(lp);
		if (!m.matches())
			throw new YangParserException("@" + getLine() + ":" + getCol()
					+ ":prefix syntax " + lp);
		prefix = lp;

	}

}
