/* Generated By:JJTree: Do not edit this line. YANG_Unique.java */
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class YANG_Unique extends SimpleNode {

	private Pattern desc_sch_nid = null;

	private String unique = null;

	public YANG_Unique(int id) {
		super(id);
		try {
			desc_sch_nid = Pattern
					.compile("(([_A-Za-z][._\\-A-Za-z0-9]*:)?[_A-Za-z][._\\-A-Za-z0-9]*((/([_A-Za-z][._\\-A-Za-z0-9]*:)?[_A-Za-z][._\\-A-Za-z0-9]*)+)?(\\s)*)*");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public YANG_Unique(yang p, int id) {
		super(p, id);
	}

	public void setUnique(String u) throws YangParserException {
		String un = YangBuiltInTypes.removeQuotesAndTrim(u);
		Matcher m = desc_sch_nid.matcher(un);
		if (m.matches())
			unique = un;
		else
			throw new YangParserException("@" + getLine() + "." + getCol()
					+ ":incorrect descendant schema node id :" + u);
	}

	public String getUnique() {
		return unique;
	}

	public void check(YangContext context) {
	}

	public String toString() {
		return "unique " + unique + ";";
	}

}
