/* Generated By:JJTree: Do not edit this line. YANG_ErrorMessage.java */

public class YANG_ErrorMessage extends SimpleNode {
	
	private String errormessage = null;
	
  public YANG_ErrorMessage(int id) {
    super(id);
  }

  public YANG_ErrorMessage(yang p, int id) {
    super(p, id);
  }
  
  public void setErrorMessage(String e){
	  errormessage = e;
  }
  
  public String getErrorMessage() {
	  return errormessage;
  }
  

	public String toString(){
		return "error-message " + errormessage + ";";
	}

}
