/* Generated By:JJTree: Do not edit this line. YANG_BitSpecification.java */
import java.util.*;

public class YANG_BitSpecification extends SimpleNode {

    private Vector<YANG_Bit> bits = new Vector<YANG_Bit>();

  public YANG_BitSpecification(int id) {
    super(id);
  }

  public YANG_BitSpecification(yang p, int id) {
    super(p, id);
  }

    public void addBit(YANG_Bit b){
	bits.add(b);
    }

    public Vector<YANG_Bit> getBits(){
	return bits;
    }

    public String toString(){
	String result = new String();
	for(Enumeration<YANG_Bit> eb = bits.elements();eb.hasMoreElements();)
	    result += eb.nextElement().toString() + "\n";
	return result;
    }

}
