/* Generated By:JJTree: Do not edit this line. YANG_CaseDef.java */

public interface  YANG_CaseDef extends Node{
	public  void check(YangContext context) throws YangParserException;
    public  String getBody();

}
