/* Generated By:JJTree: Do not edit this line. YANG_UnionSpecification.java */
import java.util.*;

public class YANG_UnionSpecification extends SimpleNode {

    private Vector<YANG_Type> types = new Vector<YANG_Type>();

  public YANG_UnionSpecification(int id) {
    super(id);
  }

  public YANG_UnionSpecification(yang p, int id) {
    super(p, id);
  }

    public void addType(YANG_Type t){
	types.add(t);
    }

    public Vector<YANG_Type> getTypes(){
	return types;
    }

    public String toString(){
	String result = new String();
	for(Enumeration<YANG_Type> et = types.elements();et.hasMoreElements();)
	    result += et.nextElement().toString() + "\n";
	return result;
    }
}
