/* Generated By:JJTree: Do not edit this line. YANG_Include.java */

public class YANG_Include extends SimpleNode implements YANG_Linkage {

	private String include = null;

	public YANG_Include(int id) {
		super(id);
	}

	public YANG_Include(yang p, int id) {
		super(p, id);
	}

	public void setIdentifier(String s) {
		include = s;
	}

	public String getIncludedModule() {
		return include;
	}

	public String toString() {
		return " include " + include + ";";
	}

}
