/* Generated By:JJTree: Do not edit this line. YANG_Description.java */

public class YANG_Description extends SimpleNode implements YANG_Meta{

    private String description = null;

  public YANG_Description(int id) {
    super(id);
  }

  public YANG_Description(yang p, int id) {
    super(p, id);
  }

    public void setDescription(String d){
	description = d;
    }

    public String getDescription(){
	return description;
    }

    public void check(YangContext context){
    }

    public String toString(){
	return "description\n\t " + description + ";";
    }
    

}
