/* Generated By:JJTree: Do not edit this line. YANG_ShortCase.java */

public interface YANG_ShortCase  extends Node{

    public void check(YangContext context) throws YangParserException;
    public String getBody();

}
