/* Generated By:JJTree: Do not edit this line. YANG_Import.java */

public class YANG_Import extends SimpleNode implements YANG_Linkage {

	private String importstr = null;
	private YANG_Prefix prefix = null;

	public YANG_Import(int id) {
		super(id);
	}

	public YANG_Import(yang p, int id) {
		super(p, id);
	}

	public void setIdentifier(String s) {
		importstr = s;
	}

	public String getImportedModule() {
		return importstr;
	}

	public void setPrefix(YANG_Prefix p) {
		prefix = p;
	}

	public YANG_Prefix getPrefix() {
		return prefix;
	}

	public String toString() {
		return " import " + importstr + " {" + prefix.toString() + "}";
	}

}
