/* Generated By:JJTree: Do not edit this line. YANG_Start.java */

public class YANG_Start extends SimpleNode {
  public YANG_Start(int id) {
    super(id);
  }

  public YANG_Start(yang p, int id) {
    super(p, id);
  }

}
