/* Generated By:JJTree: Do not edit this line. YANG_ModuleHeader.java */


public interface YANG_Header extends Node{

    public String toString();
}

/*
public class YANG_ModuleHeader extends SimpleNode {

    private YANG_YangVersion version = null;
    private YANG_NameSpace namespace = null;
    private YANG_Prefix prefix = null;

  public YANG_ModuleHeader(int id) {
    super(id);
  }

  public YANG_ModuleHeader(yang p, int id) {
    super(p, id);
  }

    public void setVersion(YANG_YangVersion v){
	version = v;
    }

    public void setNameSpace(YANG_NameSpace n){
	namespace = n;
    }

    public void setPrefix(YANG_Prefix p){
	prefix = p;
    }

    public String toString(){
	String header = new String();
	if(version != null)
	    header += " " + version.toString() + "\n";
	if(namespace != null)
	    header += " " + namespace.toString() + "\n";
	if(prefix != null)
	    header += " " + prefix.toString() + "\n";
	return header;
    }

}
*/
