import java.util.regex.PatternSyntaxException;

/* Generated By:JJTree: Do not edit this line. YANG_Key.java */

public class YANG_Key extends SimpleNode {

	private String key = null;

	public YANG_Key(int id) {
		super(id);
	}

	public YANG_Key(yang p, int id) {
		super(p, id);
	}

	public void setKey(String k) {
		key = k;
	}

	public String getKey() {
		return key;
	}

	public String[] getKeyLeaves() {
		String k = YangBuiltInTypes.removeQuotesAndTrim(getKey());
		String[] result = null;
		try{
			result = k.split("\\s+");
		} catch (PatternSyntaxException pe){
			// Cannot occurs
		}
		return result;
		
	}

	public String toString() {
		return "key " + key + ";";
	}

}
