/* Generated By:JJTree: Do not edit this line. YANG_Feature.java */

package jyang.parser;

import java.util.Vector;


public class YANG_Feature extends FeaturedBody {

	private String feature = null;

	public YANG_Feature(int id) {
		super(id);
	}

	public YANG_Feature(yang p, int id) {
		super(p, id);
	}


	public String getFeature() {
		return feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

	@Override
	public void check(YangContext context) {
		
		
	}

	@Override
	public String getBody() {
			return feature;
	}
	
	// TODO toString method

}
