/* Generated By:JJTree&JavaCC: Do not edit this line. yangTokenManager.java */
package jyang.parser;
import java.util.Enumeration;
import java.util.Vector;

/** Token Manager. */
public class yangTokenManager implements yangConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1000L) != 0L || (active1 & 0x1f8000000000000L) != 0L)
            return 61;
         if ((active0 & 0x400L) != 0L)
            return 62;
         if ((active0 & 0x800L) != 0L)
            return 63;
         if ((active1 & 0x200000000000000L) != 0L)
            return 64;
         if ((active1 & 0x4000000000000L) != 0L)
            return 19;
         if ((active0 & 0xfffffffffff80000L) != 0L || (active1 & 0x1fefffffffL) != 0L)
         {
            jjmatchedKind = 101;
            return 65;
         }
         if ((active1 & 0x10000000L) != 0L)
            return 5;
         return -1;
      case 1:
         if ((active0 & 0x1000L) != 0L)
            return 61;
         if ((active0 & 0xfffffffffff80000L) != 0L || (active1 & 0x1fefffffffL) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 1;
            return 65;
         }
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 104;
            jjmatchedPos = 1;
            return 61;
         }
         return -1;
      case 2:
         if ((active1 & 0x10000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 104;
               jjmatchedPos = 2;
            }
            return 61;
         }
         if ((active0 & 0xffcfbffffef80000L) != 0L || (active1 & 0x1f61effeffL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 101;
               jjmatchedPos = 2;
            }
            return 65;
         }
         if ((active0 & 0x30400001000000L) != 0L || (active1 & 0x8e100100L) != 0L)
            return 65;
         return -1;
      case 3:
         if ((active1 & 0x10000000L) != 0L)
            return 61;
         if ((active0 & 0xdf7a3ffefcb80000L) != 0L || (active1 & 0xb61ed66ffL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 101;
               jjmatchedPos = 3;
            }
            return 65;
         }
         if ((active0 & 0x2085800102400000L) != 0L || (active1 & 0x1400029800L) != 0L)
            return 65;
         return -1;
      case 4:
         if ((active0 & 0xdf7b1ffefcb80000L) != 0L || (active1 & 0xb60ec36fbL) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 4;
            return 65;
         }
         if ((active0 & 0x200000000000L) != 0L || (active1 & 0x1014004L) != 0L)
            return 65;
         return -1;
      case 5:
         if ((active0 & 0xcf3917fef0b00000L) != 0L || (active1 & 0x9606c14eaL) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 5;
            return 65;
         }
         if ((active0 & 0x104208000c080000L) != 0L || (active1 & 0x200802211L) != 0L)
            return 65;
         return -1;
      case 6:
         if ((active0 & 0x8f39079ea0900000L) != 0L || (active1 & 0x8604c04eaL) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 6;
            return 65;
         }
         if ((active0 & 0x4000106050200000L) != 0L || (active1 & 0x100201000L) != 0L)
            return 65;
         return -1;
      case 7:
         if ((active0 & 0xf39049ea0800000L) != 0L || (active1 & 0x8204c0428L) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 101;
               jjmatchedPos = 7;
            }
            return 65;
         }
         if ((active0 & 0x8000030000100000L) != 0L || (active1 & 0x400000c2L) != 0L)
            return 65;
         return -1;
      case 8:
         if ((active0 & 0xe30048680800000L) != 0L || (active1 & 0x204c00a0L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 8;
            return 65;
         }
         if ((active0 & 0x109001820000000L) != 0L || (active1 & 0x800000408L) != 0L)
            return 65;
         return -1;
      case 9:
         if ((active0 & 0xa30008680000000L) != 0L || (active1 & 0x200c00a0L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 9;
            return 65;
         }
         if ((active0 & 0x400040000800000L) != 0L || (active1 & 0x400000L) != 0L)
            return 65;
         return -1;
      case 10:
         if ((active0 & 0xa30008600000000L) != 0L || (active1 & 0x200400a0L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 10;
            return 65;
         }
         if ((active0 & 0x80000000L) != 0L || (active1 & 0x80000L) != 0L)
            return 65;
         return -1;
      case 11:
         if ((active0 & 0x8600000000L) != 0L || (active1 & 0x200000a0L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 11;
            return 65;
         }
         if ((active0 & 0xa30000000000000L) != 0L || (active1 & 0x40000L) != 0L)
            return 65;
         return -1;
      case 12:
         if ((active0 & 0x8000000000L) != 0L || (active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 12;
            return 65;
         }
         if ((active0 & 0x600000000L) != 0L || (active1 & 0x20000080L) != 0L)
            return 65;
         return -1;
      case 13:
         if ((active0 & 0x8000000000L) != 0L || (active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 13;
            return 65;
         }
         return -1;
      case 14:
         if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 101;
            jjmatchedPos = 14;
            return 65;
         }
         if ((active0 & 0x8000000000L) != 0L)
            return 65;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 10, 62);
      case 39:
         return jjStartNfaWithStates_0(0, 11, 63);
      case 40:
         return jjStartNfaWithStates_0(0, 119, 61);
      case 41:
         return jjStartNfaWithStates_0(0, 120, 61);
      case 43:
         return jjStartNfaWithStates_0(0, 121, 64);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000L);
      case 46:
         jjmatchedKind = 117;
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x0L);
      case 47:
         return jjStartNfaWithStates_0(0, 114, 19);
      case 58:
         return jjStopAtPos(0, 109);
      case 59:
         return jjStopAtPos(0, 113);
      case 61:
         return jjStartNfaWithStates_0(0, 118, 61);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000L);
      case 91:
         return jjStartNfaWithStates_0(0, 115, 61);
      case 93:
         return jjStartNfaWithStates_0(0, 116, 61);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x380000L, 0x100000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1c00000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3e000000L, 0x200000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x30c0000000L, 0xc00000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0xf00000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xc000000000L, 0x1000000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x3e0000000000L, 0x0L);
      case 107:
         return jjMoveStringLiteralDfa1_0(0x400000000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x7800000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0xf8000000000000L, 0x6000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x300000000000000L, 0x20000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x1c00000000000000L, 0x40000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0xe000000000000000L, 0x3L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000001fcL);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000600L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400001800L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180000e000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc0000L);
      case 123:
         return jjStopAtPos(0, 111);
      case 125:
         return jjStopAtPos(0, 112);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(1, 12, 61);
         break;
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x6118000002400000L, active1, 0xd050004L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40000000L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L, active1, 0x100000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x3c070c0800000L, active1, 0x100c000f8L);
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0x20000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x24000001000000L, active1, 0x2080000L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x300100080000L, active1, 0x800006000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x8240000038000000L, active1, 0x20000000L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0xc00018600100000L, active1, 0x400000003L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000008000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1080000000200000L, active1, 0x200400L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200001800L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0L);
      case 70:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(2, 95, 65);
         break;
      case 78:
         if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 91, 65);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x180c000000000L, active1, 0x200L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800000400L);
      case 99:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 72, 65);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L, active1, 0L);
      case 100:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 84, 65);
         return jjMoveStringLiteralDfa3_0(active0, 0x440000000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L, active1, 0x1000028003L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0x18L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000300000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x6000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L, active1, 0x1810000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0L);
      case 110:
         if ((active1 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x2a000038000000L, active1, 0xc0004L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x10004000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x280000000000L, active1, 0x100401800L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000L, active1, 0x200000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8084000082400000L, active1, 0x240000000L);
      case 116:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(2, 24, 65);
         return jjMoveStringLiteralDfa3_0(active0, 0x7200000800000000L, active1, 0x20000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L, active1, 0x400000000L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000L, active1, 0xc0L);
      case 120:
         if ((active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000L, active1, 0L);
      case 121:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 46, 65);
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000000000000L, active1, 0x20080000L);
      case 70:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 92, 61);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000040000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x8080000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 65);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 65);
         else if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 98, 65);
         return jjMoveStringLiteralDfa4_0(active0, 0x500000800000000L, active1, 0x801008L);
      case 102:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1040008000000L, active1, 0x1L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000L, active1, 0x40004L);
      case 104:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 61, 65);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x8200003004000000L, active1, 0xd0L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L, active1, 0x100000000L);
      case 109:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 65);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0x400L);
      case 110:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 81, 65);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x80600800000L, active1, 0x840000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L, active1, 0L);
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2000L);
      case 114:
         if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 100, 65);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x600000L);
      case 115:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 79, 65);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000002L);
      case 116:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 50, 65);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 55, 65);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000004030000000L, active1, 0x200004200L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x40210000100000L, active1, 0x10020L);
      case 120:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L, active1, 0x40000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x8003030000000L, active1, 0x100000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000L);
      case 101:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(4, 66, 65);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 80, 65);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 88, 65);
         return jjMoveStringLiteralDfa5_0(active0, 0x4030040000200000L, active1, 0x200680002L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L, active1, 0x21L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L, active1, 0x40000000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x180000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000800800000L, active1, 0x10L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x400080680000000L, active1, 0x8L);
      case 115:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 78, 65);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L, active1, 0x200000c0L);
      case 116:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 45, 65);
         return jjMoveStringLiteralDfa5_0(active0, 0x8002028000000000L, active1, 0x800000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000104040000000L, active1, 0x800002200L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0x600000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L, active1, 0x100400000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L, active1, 0x400L);
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 65);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 54, 65);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 65);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 77, 65);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 87, 65);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000100000L, active1, 0x40001008L);
      case 103:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 65);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L, active1, 0L);
      case 104:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 49, 65);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x8a000380a0000000L, active1, 0xc0L);
      case 108:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(5, 19, 65);
         return jjMoveStringLiteralDfa6_0(active0, 0x31000040000000L, active1, 0x80000L);
      case 109:
         if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 97, 65);
         break;
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L, active1, 0x800200002L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000004000000000L, active1, 0x20L);
      case 115:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 73, 65);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L, active1, 0L);
      case 116:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 65);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 60, 65);
         return jjMoveStringLiteralDfa6_0(active0, 0x8003000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x20000000L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x40000L);
      case 120:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(5, 64, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000200000000L, active1, 0x400000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000000L, active1, 0x2L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L, active1, 0x800000000L);
      case 101:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 65);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 38, 65);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 44, 65);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(6, 96, 65);
         return jjMoveStringLiteralDfa7_0(active0, 0x30000000000000L, active1, 0xc0020L);
      case 102:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 76, 65);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x1001800000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L, active1, 0L);
      case 110:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 62, 65);
         return jjMoveStringLiteralDfa7_0(active0, 0x10020100000L, active1, 0x8L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x8008008000000000L, active1, 0xc0L);
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L, active1, 0x20000000L);
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L, active1, 0L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 65);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 28, 65);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 65);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 85, 65);
         return jjMoveStringLiteralDfa7_0(active0, 0x60000000000L, active1, 0x40000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L);
      case 122:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000800000L, active1, 0x20L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0xa00000000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000000000L, active1, 0x8L);
      case 101:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(7, 65, 65);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 94, 65);
         return jjMoveStringLiteralDfa8_0(active0, 0x420000000L, active1, 0x800000000L);
      case 103:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 40, 65);
         break;
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x400L);
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x30000000000000L, active1, 0x80000L);
      case 110:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 63, 65);
         else if ((active1 & 0x40L) != 0L)
         {
            jjmatchedKind = 70;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000L, active1, 0x80L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L, active1, 0x20000000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000L, active1, 0x40000L);
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 20, 65);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L, active1, 0x400000L);
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000L, active1, 0L);
      case 121:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 41, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000L, active1, 0x80L);
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000000L, active1, 0L);
      case 100:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(8, 99, 65);
         break;
      case 101:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 56, 65);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(8, 67, 65);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(8, 74, 65);
         return jjMoveStringLiteralDfa9_0(active0, 0x30000000000000L, active1, 0x480000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000L, active1, 0x20L);
      case 110:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(8, 35, 65);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 36, 65);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x20000000L);
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L, active1, 0L);
      case 114:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(8, 29, 65);
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000L, active1, 0x40000L);
      case 116:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 48, 65);
         return jjMoveStringLiteralDfa9_0(active0, 0xa00000000800000L, active1, 0L);
      case 121:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 51, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L, active1, 0L);
      case 100:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(9, 86, 65);
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000L, active1, 0x80L);
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 42, 65);
         break;
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0xa00000000000000L, active1, 0x40000L);
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x30000000000000L, active1, 0x80020L);
      case 111:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(9, 23, 65);
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x20000000L);
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000L, active1, 0L);
      case 121:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 58, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000L, active1, 0x80L);
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(10, 31, 65);
         break;
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0xa00000000000000L, active1, 0x40000L);
      case 115:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x20L);
      case 116:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(10, 83, 65);
         return jjMoveStringLiteralDfa11_0(active0, 0x30000200000000L, active1, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x20000000L);
      case 103:
         return jjMoveStringLiteralDfa12_0(active0, 0x8400000000L, active1, 0L);
      case 110:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 57, 65);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 59, 65);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(11, 82, 65);
         break;
      case 115:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 52, 65);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 53, 65);
         break;
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0xa0L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, active1);
      return 12;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x20L);
      case 100:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(12, 93, 65);
         break;
      case 101:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(12, 34, 65);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(12, 71, 65);
         break;
      case 103:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(12, 33, 65);
         break;
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x8000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, active1);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(11, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, active1);
      return 13;
   }
   switch(curChar)
   {
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x20L);
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x8000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, active1);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(12, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, active1);
      return 14;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0x20L);
      case 115:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 39, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, active1);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(13, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1);
      return 15;
   }
   switch(curChar)
   {
      case 101:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(15, 69, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 61;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0xa3ffeb0000000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(14, 15);
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                     jjCheckNAddStates(3, 9);
                  }
                  else if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(2, 45);
                  else if (curChar == 47)
                     jjAddStates(10, 11);
                  if (curChar == 47)
                     jjCheckNAdd(17);
                  else if (curChar == 45)
                     jjCheckNAddStates(12, 14);
                  else if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 19:
                  if ((0xa7ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  else if (curChar == 42)
                     jjCheckNAddTwoStates(25, 26);
                  if ((0xa3ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 106)
                        kind = 106;
                     jjCheckNAdd(17);
                  }
                  if ((0xa3ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  if (curChar == 47)
                     jjCheckNAddStates(15, 17);
                  break;
               case 62:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 34)
                  {
                     if (kind > 16)
                        kind = 16;
                  }
                  break;
               case 65:
                  if ((0xa7ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0xa3ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  else if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 56;
                  if ((0x3ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  if ((0x3ff600000000000L & l) != 0L)
                  {
                     if (kind > 101)
                        kind = 101;
                     jjCheckNAdd(53);
                  }
                  break;
               case 64:
                  if ((0xa7ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0xa3ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(18, 20);
                  }
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 61:
                  if ((0xa7ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0xa3ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  break;
               case 5:
                  if ((0xa7ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0xa3ffeb0000000000L & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(18, 20);
                  }
                  else if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(8);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                     jjCheckNAdd(4);
                  }
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 6;
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 63:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(14, 15);
                  else if (curChar == 39)
                  {
                     if (kind > 16)
                        kind = 16;
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(4);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 8:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  break;
               case 10:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 12:
                  if (curChar == 34 && kind > 16)
                     kind = 16;
                  break;
               case 13:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 14:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 15:
                  if (curChar == 39 && kind > 16)
                     kind = 16;
                  break;
               case 16:
                  if (curChar == 47)
                     jjCheckNAdd(17);
                  break;
               case 17:
                  if ((0xa3ffeb0000000000L & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  jjCheckNAdd(17);
                  break;
               case 18:
                  if (curChar == 47)
                     jjAddStates(10, 11);
                  break;
               case 20:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 21:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 22:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 23:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 25:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 26:
                  if (curChar == 42)
                     jjAddStates(21, 22);
                  break;
               case 27:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 28:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               case 29:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAddStates(3, 9);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(31);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAddStates(18, 20);
                  break;
               case 46:
                  if (curChar == 46)
                     jjCheckNAdd(47);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAddTwoStates(47, 48);
                  break;
               case 49:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(50);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(50);
                  break;
               case 51:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(2, 45);
                  break;
               case 53:
                  if ((0x3ff600000000000L & l) == 0L)
                     break;
                  if (kind > 101)
                     kind = 101;
                  jjCheckNAdd(53);
                  break;
               case 54:
                  if ((0x3ff600000000000L & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  break;
               case 55:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 57:
                  if ((0x3ff600000000000L & l) == 0L)
                     break;
                  if (kind > 110)
                     kind = 110;
                  jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 58:
                  if ((0xa3ffeb0000000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  break;
               case 59:
                  if ((0xa3ffeb0000000000L & l) == 0L)
                     break;
                  if (kind > 104)
                     kind = 104;
                  jjCheckNAdd(59);
                  break;
               case 60:
                  if ((0xa7ffeb0000000000L & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAdd(60);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0x47fffffebffffffeL & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 101)
                        kind = 101;
                     jjCheckNAddStates(23, 25);
                  }
                  break;
               case 19:
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 106)
                        kind = 106;
                     jjCheckNAdd(17);
                  }
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  break;
               case 62:
                  jjCheckNAddStates(0, 2);
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 65:
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 101)
                        kind = 101;
                     jjCheckNAdd(53);
                  }
                  break;
               case 64:
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  break;
               case 61:
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  break;
               case 5:
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 107)
                        kind = 107;
                     jjCheckNAdd(60);
                  }
                  if ((0x47fffffebffffffeL & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     jjCheckNAdd(59);
                  }
                  break;
               case 63:
               case 14:
                  jjCheckNAddTwoStates(14, 15);
                  break;
               case 0:
                  if (curChar == 120)
                     jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(1);
                  break;
               case 6:
                  if (curChar == 120)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(7);
                  break;
               case 10:
                  jjCheckNAddStates(0, 2);
                  break;
               case 11:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 17:
                  if ((0x47fffffebffffffeL & l) == 0L)
                     break;
                  if (kind > 106)
                     kind = 106;
                  jjCheckNAdd(17);
                  break;
               case 20:
                  jjAddStates(15, 17);
                  break;
               case 25:
                  jjCheckNAddTwoStates(25, 26);
                  break;
               case 27:
               case 28:
                  jjCheckNAddTwoStates(28, 26);
                  break;
               case 48:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(26, 27);
                  break;
               case 52:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 101)
                     kind = 101;
                  jjCheckNAddStates(23, 25);
                  break;
               case 53:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 101)
                     kind = 101;
                  jjCheckNAdd(53);
                  break;
               case 54:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  break;
               case 56:
               case 57:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 110)
                     kind = 110;
                  jjCheckNAdd(57);
                  break;
               case 58:
                  if ((0x47fffffebffffffeL & l) != 0L)
                     jjCheckNAddTwoStates(59, 60);
                  break;
               case 59:
                  if ((0x47fffffebffffffeL & l) == 0L)
                     break;
                  if (kind > 104)
                     kind = 104;
                  jjCheckNAdd(59);
                  break;
               case 60:
                  if ((0x47fffffebffffffeL & l) == 0L)
                     break;
                  if (kind > 107)
                     kind = 107;
                  jjCheckNAdd(60);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 62:
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 63:
               case 14:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 20:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(15, 17);
                  break;
               case 25:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 27:
               case 28:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(28, 26);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 61 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   10, 11, 12, 31, 32, 41, 44, 45, 46, 48, 19, 24, 4, 5, 8, 20, 
   21, 23, 45, 46, 48, 27, 29, 53, 54, 55, 49, 50, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, "\42", "\47", 
"\56\56", null, null, null, null, null, null, "\141\156\171\170\155\154", 
"\141\162\147\165\155\145\156\164", "\141\165\147\155\145\156\164", "\142\141\163\145", 
"\142\145\154\157\156\147\163\55\164\157", "\142\151\164", "\143\141\163\145", "\143\150\157\151\143\145", 
"\143\157\156\146\151\147", "\143\157\156\164\141\143\164", "\143\157\156\164\141\151\156\145\162", 
"\144\145\146\141\165\154\164", "\144\145\163\143\162\151\160\164\151\157\156", "\145\156\165\155", 
"\145\162\162\157\162\55\141\160\160\55\164\141\147", "\145\162\162\157\162\55\155\145\163\163\141\147\145", 
"\145\170\164\145\156\163\151\157\156", "\144\145\166\151\141\164\151\157\156", "\144\145\166\151\141\164\145", 
"\146\145\141\164\165\162\145", "\146\162\141\143\164\151\157\156\55\144\151\147\151\164\163", 
"\147\162\157\165\160\151\156\147", "\151\144\145\156\164\151\164\171", "\151\146\55\146\145\141\164\165\162\145", 
"\151\155\160\157\162\164", "\151\156\143\154\165\144\145", "\151\156\160\165\164", "\153\145\171", 
"\154\145\141\146", "\154\145\141\146\55\154\151\163\164", "\154\145\156\147\164\150", 
"\154\151\163\164", "\155\141\156\144\141\164\157\162\171", 
"\155\141\170\55\145\154\145\155\145\156\164\163", "\155\151\156\55\145\154\145\155\145\156\164\163", "\155\157\144\165\154\145", 
"\155\165\163\164", "\156\141\155\145\163\160\141\143\145", 
"\156\157\164\151\146\151\143\141\164\151\157\156", "\157\162\144\145\162\145\144\55\142\171", 
"\157\162\147\141\156\151\172\141\164\151\157\156", "\157\165\164\160\165\164", "\160\141\164\150", 
"\160\141\164\164\145\162\156", "\160\157\163\151\164\151\157\156", "\160\162\145\146\151\170", 
"\160\162\145\163\145\156\143\145", "\162\141\156\147\145", "\162\145\146\145\162\145\156\143\145", 
"\162\145\146\151\156\145", "\162\145\161\165\151\162\145\55\151\156\163\164\141\156\143\145", 
"\162\145\166\151\163\151\157\156", "\162\145\166\151\163\151\157\156\55\144\141\164\145", "\162\160\143", 
"\163\164\141\164\165\163", "\163\165\142\155\157\144\165\154\145", "\164\171\160\145", 
"\164\171\160\145\144\145\146", "\165\156\151\161\165\145", "\165\156\151\164\163", "\165\163\145\163", 
"\166\141\154\165\145", "\167\150\145\156", "\171\141\156\147\55\166\145\162\163\151\157\156", 
"\171\151\156\55\145\154\145\155\145\156\164", "\141\144\144", "\143\165\162\162\145\156\164", 
"\144\145\160\162\145\143\141\164\145\144", "\144\145\154\145\164\145", "\146\141\154\163\145", "\155\151\156", 
"\155\141\170", "\116\141\116", "\55\111\116\106", 
"\156\157\164\55\163\165\160\160\157\162\164\145\144", "\157\142\163\157\154\145\164\145", "\111\116\106", 
"\162\145\160\154\141\143\145", "\163\171\163\164\145\155", "\164\162\165\145", 
"\165\156\142\157\165\156\144\145\144", "\165\163\145\162", null, null, null, null, null, null, null, null, "\72", 
null, "\173", "\175", "\73", "\57", "\133", "\135", "\56", "\75", "\50", "\51", 
"\53", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xfffffffffffbfd81L, 0x3ffed3fffffffffL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[61];
static private final int[] jjstateSet = new int[122];
static protected char curChar;
/** Constructor. */
public yangTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public yangTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 61; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
