/* Generated By:JJTree&JavaCC: Do not edit this line. yangConstants.java */
package jyang;

public interface yangConstants {

  int EOF = 0;
  int DECVALUE = 7;
  int NEGDECVALUE = 8;
  int NONZERO = 9;
  int DQUOTE = 10;
  int SQUOTE = 11;
  int DDOT = 12;
  int DATE = 13;
  int FDIGIT = 14;
  int TDIGIT = 15;
  int STRING = 16;
  int FLOAT = 17;
  int EXPONENT = 18;
  int anyxmlkeyword = 19;
  int argumentkeyword = 20;
  int augmentkeyword = 21;
  int basekeyword = 22;
  int belongstokeyword = 23;
  int bitkeyword = 24;
  int casekeyword = 25;
  int choicekeyword = 26;
  int configkeyword = 27;
  int contactkeyword = 28;
  int containerkeyword = 29;
  int defaultkeyword = 30;
  int descriptionkeyword = 31;
  int enumkeyword = 32;
  int errorapptagkeyword = 33;
  int errormessagekeyword = 34;
  int extensionkeyword = 35;
  int deviationkeyword = 36;
  int deviatekeyword = 37;
  int featurekeyword = 38;
  int groupingkeyword = 39;
  int identitykeyword = 40;
  int iffeaturekeyword = 41;
  int importkeyword = 42;
  int includekeyword = 43;
  int inputkeyword = 44;
  int keykeyword = 45;
  int leafkeyword = 46;
  int leaflistkeyword = 47;
  int lengthkeyword = 48;
  int listkeyword = 49;
  int mandatorykeyword = 50;
  int maxelementskeyword = 51;
  int minelementskeyword = 52;
  int modulekeyword = 53;
  int mustkeyword = 54;
  int namespacekeyword = 55;
  int notificationkeyword = 56;
  int orderedbykeyword = 57;
  int organizationkeyword = 58;
  int outputkeyword = 59;
  int pathkeyword = 60;
  int patternkeyword = 61;
  int positionkeyword = 62;
  int prefixkeyword = 63;
  int presencekeyword = 64;
  int rangekeyword = 65;
  int referencekeyword = 66;
  int refinekeyword = 67;
  int revisionkeyword = 68;
  int rpckeyword = 69;
  int statuskeyword = 70;
  int submodulekeyword = 71;
  int typekeyword = 72;
  int typedefkeyword = 73;
  int uniquekeyword = 74;
  int unitskeyword = 75;
  int useskeyword = 76;
  int valuekeyword = 77;
  int whenkeyword = 78;
  int yangversionkeyword = 79;
  int yinelementkeyword = 80;
  int addkeyword = 81;
  int currentkeyword = 82;
  int deprecatedkeyword = 83;
  int deletekeyword = 84;
  int falsekeyword = 85;
  int minkeyword = 86;
  int maxkeyword = 87;
  int nankeyword = 88;
  int neginfkeyword = 89;
  int notsupportedkeyword = 90;
  int obsoletekeyword = 91;
  int posinfkeyword = 92;
  int replacekeyword = 93;
  int systemkeyword = 94;
  int thisvariablekeyword = 95;
  int truekeyword = 96;
  int unboundedkeyword = 97;
  int userkeyword = 98;
  int IDENTIFIER = 99;
  int LETTER = 100;
  int DIGIT = 101;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<DECVALUE>",
    "<NEGDECVALUE>",
    "<NONZERO>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"..\"",
    "<DATE>",
    "<FDIGIT>",
    "<TDIGIT>",
    "<STRING>",
    "<FLOAT>",
    "<EXPONENT>",
    "\"anyxml\"",
    "\"argument\"",
    "\"augment\"",
    "\"base\"",
    "\"belongs-to\"",
    "\"bit\"",
    "\"case\"",
    "\"choice\"",
    "\"config\"",
    "\"contact\"",
    "\"container\"",
    "\"default\"",
    "\"description\"",
    "\"enum\"",
    "\"error-app-tag\"",
    "\"error-message\"",
    "\"extension\"",
    "\"deviation\"",
    "\"deviate\"",
    "\"feature\"",
    "\"grouping\"",
    "\"identity\"",
    "\"if-feature\"",
    "\"import\"",
    "\"include\"",
    "\"input\"",
    "\"key\"",
    "\"leaf\"",
    "\"leaf-list\"",
    "\"length\"",
    "\"list\"",
    "\"mandatory\"",
    "\"max-elements\"",
    "\"min-elements\"",
    "\"module\"",
    "\"must\"",
    "\"namespace\"",
    "\"notification\"",
    "\"ordered-by\"",
    "\"organization\"",
    "\"output\"",
    "\"path\"",
    "\"pattern\"",
    "\"position\"",
    "\"prefix\"",
    "\"presence\"",
    "\"range\"",
    "\"reference\"",
    "\"refine\"",
    "\"revision\"",
    "\"rpc\"",
    "\"status\"",
    "\"submodule\"",
    "\"type\"",
    "\"typedef\"",
    "\"unique\"",
    "\"units\"",
    "\"uses\"",
    "\"value\"",
    "\"when\"",
    "\"yang-version\"",
    "\"yin-element\"",
    "\"add\"",
    "\"current\"",
    "\"deprecated\"",
    "\"delete\"",
    "\"false\"",
    "\"min\"",
    "\"max\"",
    "\"NaN\"",
    "\"-INF\"",
    "\"not-supported\"",
    "\"obsolete\"",
    "\"INF\"",
    "\"replace\"",
    "\"system\"",
    "\"$this\"",
    "\"true\"",
    "\"unbounded\"",
    "\"user\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"/\"",
    "\".\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+\"",
  };

}
