/* Generated By:JJTree: Do not edit this line. YANG_Identity.java */

package jyang;

public class YANG_Identity extends SimpleNode {
  public YANG_Identity(int id) {
    super(id);
  }

  public YANG_Identity(yang p, int id) {
    super(p, id);
  }

}
