/* Generated By:JJTree: Do not edit this line. YANG_Identity.java */

package jyang;

public class YANG_Identity extends YANG_Body {

	private String identity = null;

	private YANG_Base base = null;

	private YANG_Status status = null;

	private YANG_Description description = null;

	private YANG_Reference reference = null;

	private boolean b_base = false, b_status = false, b_description = false,
			b_reference = false;

	public YANG_Identity(int id) {
		super(id);
	}

	public YANG_Identity(yang p, int id) {
		super(p, id);
	}

	public void setIdentity(String i) {
		identity = i;
	}

	public void setBase(YANG_Base b)  throws YangParserException {
		if (b_base)
			throw new YangParserException(
					"Base is already defined in identity " + identity, b
							.getLine(), b.getCol());
		base = b;
		b_base = true;
	}

	public void setStatus(YANG_Status s) {
		status = s;
	}

	public void setDescription(YANG_Description d) {
		description = d;
	}

	public void setReference(YANG_Reference r) {
		reference = r;
	}

	@Override
	public void check(YangContext context) throws YangParserException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getBody() {
		return identity;
	}

}
